import {useState,useRef} from 'react';
import Markdown from 'react-markdown';
import data from '../../content/atlas/model.json';
import verification from '../../data/verification.json';
import claimKo from '../../content/architecture/claims-ko-KR.json';
import {Term} from '../docs/Term';
import {githubLink} from '../docs/helpers';
import {classification} from '../docs/ia';
import {atlasState,atlasHref,atlasReturnHref,validReturn,type Axis,type AtlasState} from './state';
import type {Language} from '../i18n';
import './atlas.css';
type Node={id:string;labels:Record<Language,string>;content:Record<Language,string>;branches:string[];referenceIds:string[];claimIds:string[];architectureNodeIds:string[];term?:string;documentId?:string;opposite?:{axis:string;node:string}};
const nodes=data.nodes as Node[];
const byId=new Map(nodes.map(n=>[n.id,n]));
const prose=import.meta.glob('../../content/atlas/{ko-KR,en}/*.md',{query:'?raw',import:'default',eager:true}) as Record<string,string>;
export function AtlasReturn({lang}:{lang:Language}){const href=atlasReturnHref(lang);return href?<nav className="atlas-return"><a href={href}>{lang==='en'?'← Return to the selected roadmap stage':'← 선택했던 지도 단계로 돌아가기'}</a></nav>:null;}
export function AtlasHome({lang}:{lang:Language}){return <main className="atlas-home"><small>SYSTEM ATLAS · M1–M2</small><h1>Knowledge OS</h1><p>{lang==='en'?'See the whole system, then follow a question into its implementation and evidence.':'전체를 먼저 보고, 궁금한 단계에서 구현과 검증까지 따라갑니다.'}</p><div>{(['runtime','engineering'] as Axis[]).map(a=><a key={a} href={`#/${lang}/${a}`}><h2>{a==='runtime'?(lang==='en'?'How does the system work?':'시스템은 실제로 어떻게 동작하나요?'):(lang==='en'?'How was it built and verified?':'어떻게 만들었고 어디까지 검증됐나요?')}</h2><span>{a==='runtime'?'Runtime Roadmap':'Engineering Roadmap'} →</span></a>)}</div></main>;}
function Topology({lang}:{lang:Language}){const ko=lang==='ko-KR';return <section className="atlas-topology" aria-label={ko?'전체 시스템 구조':'Whole system topology'}><div className="atlas-outside"><strong>Notion · Google Drive · Files</strong><small>{ko?'시스템 바깥 · 원본은 여기 남음':'Outside the system · originals remain here'}</small></div><span>↓ {ko?'관찰·수집':'Observe / ingest'}</span><div className="atlas-system"><strong>Knowledge OS</strong><span>{ko?'근거 수집·보존 / 제한된 조회·관리':'Preserve evidence / bounded reads and governance'}</span><span>↕</span><strong>Neo4j</strong><small>{ko?'근거·관계·이력 저장':'Stores evidence, relationships and history'}</small></div><span>↕ {ko?'질문·근거 반환':'Question / returned evidence'}</span><div>{ko?'나':'Me'} ↔ Claude/GPT ↔ {ko?'MCP':'MCP'}</div><p>{ko?'수집은 원문에서, 질문은 나에게서 시작합니다. AI가 저장소를 직접 임의 조회하지 않습니다.':'Ingestion starts at the source; a question starts with me. The AI does not query the store arbitrarily.'}</p></section>;}
export default function Atlas({lang,axis}:{lang:Language;axis:Axis}){
 const ko=lang==='ko-KR',s={...atlasState(),axis},base=data.backbones[axis];
 const selected=trail(s.node)?byId.get(s.node):undefined,root=base.includes(s.root)?s.root:trail(s.node)?.[0]||'';
 const [zoom,setZoom]=useState(1),[search,setSearch]=useState('');const viewport=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const go=(next:Partial<AtlasState>)=>{location.hash=atlasHref(lang,{...s,...next})};
 function trail(id:string,path:string[]=[]):string[]|null {if(base.includes(id))return [id];if(path.includes(id))return null;for(const b of [...new Set([s.root,...base].filter(x=>base.includes(x)))]){const walk=(n:string,seen:string[]):string[]|null=>{if(n===id)return [...seen,n];for(const c of byId.get(n)?.branches||[]){if(seen.includes(c))continue;const found=walk(c,[...seen,n]);if(found)return found}return null};const found=walk(b,[]);if(found)return found}return null}
 const select=(id:string)=>{const p=trail(id);if(!p)return;go({node:id,root:p[0],open:[...new Set([...p,...(s.root===p[0]?s.open:[])]) ]})};
 s.open=[...new Set([...s.open,...(trail(s.node)?.slice(0,-1)||[])])];
 const branchNodes:{node:Node;depth:number;parent:string}[]=[];
 function visit(id:string,depth:number){if(!s.open.includes(id))return;for(const child of byId.get(id)?.branches||[]){branchNodes.push({node:byId.get(child)!,depth,parent:id});visit(child,depth+1)}}
 if(root)visit(root,1);
 const currentTrail=selected?trail(selected.id)||[]:[];
 const allPaths=nodes.filter(n=>trail(n.id));const results=search?allPaths.filter(n=>(n.labels[lang]+' '+n.id).toLowerCase().includes(search.toLowerCase())):[];
 const context=atlasHref(lang,s).replace(`#/${lang}/`,'');
 const ref=(path:string)=>`#/${lang}/${path}?atlas=${encodeURIComponent(context)}`;
 function opposite(){if(!selected?.opposite)return;const target=selected.opposite;const back=s.returnTo||context;const node=target.node;location.hash=atlasHref(lang,{axis:target.axis as Axis,node,root:target.axis==='runtime'?'support':'rules',open:target.axis==='runtime'?['support','evidence','version']:['rules','version-rule'],returnTo:back})}
 const origin=s.returnTo&&validReturn(s.returnTo)?`#/${lang}/${s.returnTo}`:null;
 function collapse(id:string){const removed=new Set<string>();const collect=(x:string)=>{removed.add(x);for(const c of byId.get(x)?.branches||[])collect(c)};collect(id);go({open:s.open.filter(x=>!removed.has(x)),node:currentTrail.includes(id)?id:s.node})}
 const button=(n:Node,branch=false)=> <button type="button" className={`atlas-stop ${s.node===n.id?'selected':''} ${currentTrail.includes(n.id)?'ancestor':''}`} aria-pressed={s.node===n.id} onClick={()=>select(n.id)}><span aria-hidden="true">{s.node===n.id?'●':'○'}</span>{n.labels[lang]}{branch&&<small>{ko?'상세 가지':'Detail branch'}</small>}</button>;
 return <main className="atlas" onKeyDown={e=>{if(e.key==='Escape'){go({node:''})}}}><div className="atlas-title"><div><small>{axis==='runtime'?'RUNTIME ROADMAP':'ENGINEERING ROADMAP'} · M2</small><h1>{axis==='runtime'?(ko?'질문해서 읽기':'Ask and read'):(ko?'규칙에서 구현·검증까지':'From rules to implementation and proof')}</h1></div><a href={`#/${lang}`}>{ko?'두 지도 입구':'Atlas entrance'} ↑</a></div>
 <p className="atlas-scope">{axis==='runtime'?(ko?'질문 경로를 따라 근거와 당시 문서 상태를 확인하세요. 대화 전체의 자동 실행을 보장하는 그림은 아닙니다.':'Follow a question to its evidence and document state. This does not promise a fully automatic conversation.'):(ko?'전체 기준선은 모두 보입니다. M2의 상세는 문서 버전 보존의 규칙·코드·검사·실행 근거입니다.':'The complete backbone is visible. M2 details document-version rules, storage code, integrity tests and executed evidence.')}</p>
 {origin&&<a className="atlas-original" href={origin}>{ko?'← 처음 선택했던 질문 흐름으로 복귀':'← Return to my original question flow'}</a>}
 <div className="atlas-toolbar"><label>{ko?'지도에서 찾기':'Search roadmap'}<input type="search" placeholder={ko?'근거, 문서 상태…':'Evidence, document state…'} value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={()=>setZoom(Math.max(.7,zoom-.1))} aria-label={ko?'축소':'Zoom out'}>−</button><output>{Math.round(zoom*100)}%</output><button onClick={()=>setZoom(Math.min(1.5,zoom+.1))} aria-label={ko?'확대':'Zoom in'}>＋</button><button onClick={()=>{const v=viewport.current;if(v){setZoom(Math.min(1,v.clientHeight/(base.length*66+28),v.clientWidth/(branchNodes.length?660:260)));v.scrollTo(0,0)}}}>{ko?'전체 맞춤':'Fit backbone'}</button><button onClick={()=>go({node:'',root:'',open:[]})}>{ko?'기준선만 보기':'Collapse to backbone'}</button></div>
 {search&&<div className="atlas-search" role="status">{results.length?results.map(n=><button key={n.id} onClick={()=>{select(n.id);setSearch('')}}>{n.labels[lang]}</button>):ko?'일치하는 단계가 없습니다.':'No stages match.'}</div>}
 {<nav className="atlas-position" aria-label={ko?'항상 보이는 현재 경로':'Persistent current path'}>{currentTrail.map((id,i)=><span key={id}>{i>0?' → ':''}<button onClick={()=>select(id)}>{byId.get(id)?.labels[lang]}</button></span>)}</nav>}
 <div className={`atlas-layout ${selected?'with-detail':''}`}><aside><Topology lang={lang}/>{axis==='engineering'&&<p className="atlas-scope">{ko?'릴리스 승인 미실행 · 문서 배포와 별개':'Release acceptance unexecuted · separate from documentation deployment'}</p>}</aside>
 <div className="atlas-viewport" ref={viewport} tabIndex={0} onPointerDown={e=>{if((e.target as HTMLElement).closest('button,a,input'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current){e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} aria-label={ko?'이동 가능한 로드맵':'Scrollable roadmap'} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const i=Math.max(0,base.indexOf(s.node));select(base[Math.min(base.length-1,Math.max(0,i+(e.key==='ArrowDown'?1:-1)))])}}}>
 <div className="atlas-map" style={{width:branchNodes.length?660:260,minHeight:base.length*66+28,zoom}}><svg className="atlas-lines" width="100%" height="100%" aria-hidden="true"><defs><marker id="atlas-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="currentColor"/></marker></defs>{base.slice(1).map((id,i)=><path key={id} d={`M 126 ${i*66+56} V ${(i+1)*66+8}`} markerEnd="url(#atlas-arrow)"/>)}{branchNodes.map((b,i)=>{const parent=branchNodes.findIndex(x=>x.node.id===b.parent);const y=i*96+54;return <path key={b.node.id} d={parent<0?`M 236 ${base.indexOf(root)*66+32} H 278 V ${y} H 301`:`M 591 ${parent*96+54} H 620 V ${y} H 591`} markerEnd="url(#atlas-arrow)"/>})}</svg>
 <ol className="atlas-backbone" aria-label={ko?'전체 기준선':'Complete backbone'}>{base.map(id=><li key={id}>{button(byId.get(id)!)}<span className="atlas-order">{base.indexOf(id)+1}</span></li>)}</ol>
 {root&&branchNodes.length>0&&<section className="atlas-branches" aria-label={ko?'선택한 본선의 가지':'Branches of the selected backbone stage'}><small>{byId.get(root)?.labels[lang]} →</small>{branchNodes.map(b=><div className="atlas-branch" key={b.node.id}>{button(b.node,true)}{b.node.branches.length>0&&s.open.includes(b.node.id)&&<button className="atlas-collapse" onClick={()=>collapse(b.node.id)}>{ko?'아래 가지 접기':'Collapse descendants'}</button>}</div>)}<button className="atlas-collapse" onClick={()=>collapse(root)}>{ko?'가지 전체 접기':'Collapse branch'}</button></section>}
 </div></div>
 {selected&&<aside className="atlas-drawer" aria-label={ko?'선택한 단계 설명':'Selected stage details'}><button className="atlas-close" onClick={()=>go({node:''})}>{ko?'설명 닫기':'Close details'} ×</button><nav aria-label={ko?'현재 위치':'Current position'}>{currentTrail.map((id,i)=><span key={id}>{i>0?' › ':''}<button onClick={()=>select(id)}>{byId.get(id)?.labels[lang]}</button></span>)}</nav><h2>{selected.labels[lang]}</h2><Markdown>{prose[`../../content/atlas/${selected.content[lang]}`]}</Markdown><p className="atlas-neighbors">{ko?'앞 / 뒤':'Before / after'}: {currentTrail.length>1?byId.get(currentTrail.at(-2)!)?.labels[lang]:byId.get(base[base.indexOf(selected.id)-1])?.labels[lang]||'—'} → <strong>{selected.labels[lang]}</strong> → {selected.branches.map(id=>byId.get(id)?.labels[lang]).join(' / ')||(base.includes(selected.id)?byId.get(base[base.indexOf(selected.id)+1])?.labels[lang]:(ko?'본선으로 복귀':'Return to backbone'))||'—'}</p>
 {selected.term&&<details><summary>{ko?'기술적으로 보기':'Technical view'}</summary><Term id={selected.term} lang={lang} href={selected.documentId?ref(classification(selected.documentId)?.path||'reference'):undefined}>{selected.labels[lang]}</Term></details>}
 {!!selected.referenceIds.length&&<details><summary>{ko?'구현·테스트·계약 근거':'Implementation, tests and contracts'}</summary><p>{ko?'파일·테스트의 존재는 통과 결과가 아닙니다.':'Files and tests are not passing results.'}</p>{selected.referenceIds.map(id=><div className="atlas-ref" key={id}><a href={ref('reference/item/'+encodeURIComponent(id))}>{id.slice(4)}</a>{githubLink(id)!=='#'&&<a href={githubLink(id)} target="_blank" rel="noreferrer">GitHub · {ko?'공개 근거 스냅샷':'public evidence snapshot'} ↗</a>}</div>)}<p>{ko?'현재 로컬 구현과 공개 GitHub 스냅샷의 리비전은 구별됩니다.':'Current local implementation and the public GitHub snapshot have distinct revisions.'}</p></details>}
 {selected.claimIds.map(id=>{const c=verification.claims.find(c=>c.id===id)!;const text=ko?(claimKo as Record<string,{scope:string;recordedOutcome:string;limitations:string}>)[id]:c;return <details key={id}><summary>{ko?'실행·검증 근거':'Executed verification evidence'} · {id}</summary><strong>{c.status}</strong><p>{text.scope}</p><p>{text.recordedOutcome}</p><p>{text.limitations}</p><a href={ref('reference/item/'+id)}>{ko?'정확한 범위·테스트·리비전':'Exact scope, tests and revision'} →</a></details>})}
 <details><summary>{ko?'아키텍처에서 이 기능 보기':'Inspect this feature in Architecture'}</summary>{selected.architectureNodeIds.map(id=><a key={id} href={ref('explore/node/'+encodeURIComponent(id))}>{ko?'구현 관계 탐색':'Explore implementation relationships'} → {id}</a>)}</details>
 {selected.documentId&&<a className="atlas-deep" href={ref(classification(selected.documentId)?.path||'reference')}>{ko?'기존 상세 문서 보기':'Read the preserved detailed document'} →</a>}
 {selected.opposite&&<button className="atlas-cross" onClick={opposite}>{axis==='runtime'?(ko?'이 기능의 구현·검증 보기 →':'See how this is implemented and verified →'):(ko?'이 기능이 동작하는 흐름 보기 →':'See this feature in the runtime flow →')}</button>}
 {!selected.branches.length&&!selected.referenceIds.length&&!selected.claimIds.length&&!selected.documentId&&<small>{ko?'M2: 전체 흐름 안내. 이 단계의 추가 상세는 후속 범위입니다.':'M2: backbone orientation. Further detail is outside this milestone.'}</small>}
 </aside>}
 </div></main>;
}
