import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,cpSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {checkAtlas} from '../scripts/check-atlas.mjs';
const architecture=JSON.parse(readFileSync('data/architecture.json'));
test('Atlas includes six journeys, both backbones and all 77 classifications',()=>assert.deepEqual(checkAtlas('..',architecture),{nodes:116,runtime:8,engineering:10,legacy:77,journeys:6}));
function rejects(fn,error){const root=mkdtempSync(join(tmpdir(),'atlas-check-'));try{cpSync('content',join(root,'architecture-explorer/content'),{recursive:true});const file=join(root,'architecture-explorer/content/atlas/model.json'),m=JSON.parse(readFileSync(file));fn(m);writeFileSync(file,JSON.stringify(m));assert.throws(()=>checkAtlas(root,architecture),error)}finally{rmSync(root,{recursive:true,force:true})}}
test('cannot omit a major engineering stage',()=>rejects(m=>m.backbones.engineering.pop(),/Complete Atlas backbones/));
test('cross-roadmap targets must be reachable',()=>rejects(m=>m.nodes.find(n=>n.id==='version').opposite.node='question',/cross-roadmap/));
test('renamed symbols and tests fail references',()=>rejects(m=>m.nodes.find(n=>n.id==='version-code').referenceIds=['ref:src/knowledge_os/graph.py::renamed'],/Broken Atlas reference/));
test('branch cycles fail before rendering',()=>rejects(m=>m.nodes.find(n=>n.id==='version').branches.push('support'),/cycle/));
test('prose and labels need explicit bilingual reconciliation',()=>rejects(m=>m.nodes[0].labels.en='Altered label',/review required/));
test('Atlas cannot supply its own VERIFIED status',()=>rejects(m=>m.nodes[0].status='VERIFIED',/schema/));
test('directional backbone links are mandatory',()=>rejects(m=>m.edges.shift(),/directed backbone/));
test('all six runtime journeys are required',()=>rejects(m=>m.journeys[1].id='read',/six runtime journeys/));
test('journey sequence arrows cannot disappear',()=>rejects(m=>{m.edges=m.edges.filter(e=>e.journey!=='ingest')},/directed journey/));
test('cross-roadmap links target a stage in the specified journey',()=>rejects(m=>{m.nodes.find(n=>n.id==='executor').opposite.journey='read'},/cross-roadmap/));
test('hidden branches need directional edges',()=>rejects(m=>{m.edges=m.edges.filter(e=>e.id!=='recovery-branch-backup-set')},/directed branch/));
test('comprehension checks must match the selected language',()=>rejects(m=>{m.journeys[0].checkContent.en='checks/ko-KR/read.md'},/comprehension/));
